name: deploy-dist
on: push
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: "greet user"
              run: echo "Hello worl!"
            
                

        

            
        

            

           

        




